version: '3.7'

# Amazon restricts sending of email to 25 ports for new accounts, be informed
# Helpful: https://4te.me/post/postfix-docker-ptr-spf-dkim-dmarc/

services:
  smtp:
    image: marvambass/versatile-postfix
    container_name: smtp
    restart: always
    command: ['example.com', 'no-reply:pass', 'info:pass']
    #dns:
    #  - 8.8.8.8
    ports:
      - "127.0.0.1:25:25"
    environment:
      - POSTFIX_RAW_CONFIG_SMTPD_USE_TLS=no
      - POSTFIX_RAW_CONFIG_INET_PROTOCOLS=ipv4
      - ALIASES=postmaster:root;hostmaster:root;webmaster:root
    volumes:
      - ./maildirs:/var/mail
      - ./dkim:/etc/postfix/dkim/
      #- ./resolv.conf:/etc/resolv.conf
