version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - TZ=Europe/Kiev
    ports:
      - 3380:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - HIDE_PHP_VERSION=true
      - UPLOAD_LIMIT=52428800 # 50 mb
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - 8001:80
    volumes:
      - pma_data:/sessions
    depends_on:
      - mysql

volumes:
  mysql_data:
  pma_data:
