---
- name: Configure admin user password
  uri:
    url: "{{ portainer_endpoint }}/users/admin/init"
    method: POST
    return_content: true
    body_format: json
    body: '{ "Username":"{{ admin_user }}", "Password":"{{ admin_password }}"}'
    status_code: 200, 409
