version: '3'

services:
  faktory:
    image: contribsys/faktory:latest
    container_name: faktory
    restart: always
    ports:
      - 7419:7419
      - 7420:7420
    environment:
      - FAKTORY_PASSWORD=pwd
    volumes:
      - faktory_data:/var/lib/faktory
    command: [ "/faktory", "-b", ":7419", "-w", ":7420", "-e", "production" ]

volumes:
  faktory_data:
