version: '3'

services:
  netdata:
    image: netdata/netdata
    hostname: example.com
    restart: always
    ports:
      - 8002:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
