version: '3'

services:
  netdata:
    image: netdata/netdata
    hostname: example.com
    container_name: netdata
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - 8002:19999
    logging:
      options:
        max-size: 10m
        max-file: 3
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
