version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: forum-mysql-8.0
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=forum
      - MYSQL_USER=forum
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - TZ=Europe/Kiev
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
     - PMA_HOST=mysql
     - HIDE_PHP_VERSION=true
     - UPLOAD_LIMIT=52428800 # 50 mb
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_USER=
     - MYSQL_PASSWORD=
    restart: always
    ports:
     - 8001:80
    volumes:
     - pma_data:/sessions
    depends_on:
      - mysql

volumes:
  mysql_data:
  pma_data:
