version: '3'

services:
  sentry_base:
    image: sentry:9.1.2
    container_name: sentry_base
    restart: always
    depends_on:
      - sentry_redis
      - sentry_postgres
    ports:
      - 9898:9000
    env_file:
      - sentry.env
    volumes:
      - sentry_data:/var/lib/sentry/files

  sentry_cron:
    image: sentry:9.1.2
    container_name: sentry_cron
    restart: always
    depends_on:
      - sentry_base
    command: 'sentry run cron'
    env_file:
      - sentry.env
    volumes:
      - sentry_data:/var/lib/sentry/files

  sentry_worker:
    image: sentry:9.1.2
    container_name: sentry_worker
    restart: always
    depends_on:
      - sentry_base
    command: 'sentry run worker'
    env_file:
      - sentry.env
    volumes:
      - sentry_data:/var/lib/sentry/files

  sentry_redis:
    image: redis:3
    container_name: sentry_redis
    restart: always
    command: 'redis-server --appendonly yes'

  sentry_postgres:
    image: postgres:9-alpine
    container_name: sentry_postgres
    restart: always
    env_file:
      - sentry.env
    volumes:
      - sentry_pg:/var/lib/postgresql/data

  sentry_phppgadmin:
    image: dockage/phppgadmin:latest
    container_name: sentry_pgadmin
    env_file:
      - sentry.env
    ports:
      - 9899:80
    depends_on:
      - sentry_postgres

volumes:
  sentry_data:
  sentry_pg:
