galaxy_info:
  author: Antonio Barbaro
  description: Install essential tools
  license: BSD

  min_ansible_version: 1.9

  platforms:
  - name: EL
    versions:
    - 7


  galaxy_tags: 
    - tools

dependencies: []
