version: '3'

services:
  beanstalkd:
    image: easypost/beanstalkd
    container_name: beanstalkd
    restart: always
    ports:
      - 11300:11300
    logging:
      options:
        max-size: 10m
        max-file: 3
    volumes:
      - beanstalkd_data:/data

  beanstalkd_console:
    image: ashve/beanstalkd-console
    container_name: beanstalkd_console
    restart: always
    environment:
      - BEANSTALKD_PORT_11300_TCP_ADDR=beanstalkd
    ports:
      - 8004:2080
    logging:
      options:
        max-size: 10m
        max-file: 3
    depends_on:
      - beanstalkd

volumes:
  beanstalkd_data:
